version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mkdirp
    versions:
    - ">= 1.0.a, < 1.1"
  - dependency-name: rollup
    versions:
    - "> 0.34.13"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
  - dependency-name: less
    versions:
    - 4.1.0
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
